version: '3.8'

services:
    laravel_project_boilerplate:
        build: ./
        container_name: laravel_project_boilerplate
        volumes:
            - ./:/var/www
        networks:
            - shared_network

    laravel_project_boilerplate_nginx:
        image: nginx:alpine
        container_name: laravel_project_boilerplate_nginx
        ports:
            - "8082:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel_project_boilerplate
        networks:
            - shared_network
networks:
    shared_network:
        external: true
        name: shared_network